services:
  library_api:
    container_name: library_api
    build:
      context: api/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    networks:
      - library-net
    depends_on:
      - library_db
  library_ui:
    container_name: library_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - library-net
    depends_on:
      - library_api
  library_db:
    container_name: library_db
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-library}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - library-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - library-net
    restart: always

volumes:
  library-data:

networks:
  library-net:
